Write-Host "Start supporting infrastructure first:"
Write-Host "docker compose -f infra/docker-compose.yml up -d postgres redis minio"
Write-Host ""
Write-Host "Then run services in separate terminals:"
Write-Host "API:     cd apps/api; uvicorn app.main:app --reload --port 8000"
Write-Host "Trading: cd apps/trading; python -m nautilus_runner.main"
Write-Host "Workers: cd apps/workers; python -m jobs.daily_refresh"
Write-Host "DryRun:  cd apps/workers; python -m jobs.backfill --dry-run"
Write-Host "Web:     cd apps/web; npm run start"
